# Site settings
title: maru's blog 
url: "https://gonggit.github.io"
baseurl: ""
description: >
    3년차 아빠 겸 개발자 블로그

# My information
email: gong.snucse@gmail.com
author: maru 
profile: 초보아빠 
github_username: gonggit 
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  math_engine: mathjax

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: gonggit/gonggit.github.io
  repo_id: R_kgDOI62UXA
  category: General
  category_id: DIC_kwDOI62UXM4CUFtx

google_analytics:
  ua: SAMPLE-VALUE
  encrypted_ua: THIS-IS-SAMPLE-VALUE

google_adsense:
  client: SAMPLE-VALUE

blame: "https://github.com/gonggit/gonggit.github.io/blame/master/_wiki"
edit: "https://github.com/gonggit/gonggit.github.io/edit/master/_wiki"
issue: "https://github.com/gonggit/gonggit.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]
